### ISSUE TITLE
Ambiguous start state in Python Implementation.

### ISSUE THREAD

**Issue by sujanchegu** [MadhavJivrajani/simDFA#6]
`Python/dfa.py`, Line 32:

```
    def add_state(self, is_start, is_final, name):
        if name not in self.states:
            self.states[name] = State(is_start, is_final, name)
        else:
            print("State already exists!")
```
Shouldn't we check if any other state has already been marked as Start State?
Maybe the assumption is that that the automaton user inputs is correct but why not add this check?

**Comment by MadhavJivrajani** [comment]
Hmm that's a valid point, but instead of checking if any other state has been marked, we can add a check to ensure that there's _exactly_ one start state that's provided to the DFA because an automaton by definition will have only one start start iirc, the assumption that the user enters a correct start state will have to be made in either case imo. Let me know what you think!

**Comment by sujanchegu** [comment]
Right! That even takes care of the case if there are no start states at all. Maybe that's a better idea.

**Comment by MadhavJivrajani** [comment]
You can take that up if you're interested!
Open a new issue describing the same if possible :smile:

**Comment by sujanchegu** [comment]
Right.
